version: build-{build}.{branch}
image: Visual Studio 2017

environment:
  matrix:

install:
  - ps: |
      [Environment]::SetEnvironmentVariable('dockerImage', ('python:{0}' -f $env:version), [EnvironmentVariableTarget]::Process);
      [Environment]::SetEnvironmentVariable('buildDirectory', ('{0}/windows/{1}' -f $env:version, $env:variant), [EnvironmentVariableTarget]::Process);

build_script:
  - cmd: appveyor-retry docker build --pull -t %dockerImage% %buildDirectory%

after_build:
  - ps: docker images

test_script:
  - cmd: docker run --rm %dockerImage% python --version
  - cmd: docker run --rm %dockerImage% pip freeze --all
