pipeline:
  build:
    image: dunecommunity/gitlabci_dockerindocker-dockerindocker
    commands:
      - apk add bash
      - echo $DOCKER_PW | docker login --username="$DOCKER_USER" --password-stdin
      - make python-$PY
      - make push-python-$PY

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    secrets: [ docker_user, docker_pw ]

  notify:
    image: drillster/drone-email
    host: mail.milk.pm
    from: drone@pymor.org
    when:
      status: [ changed, failure ]
    secrets:  [ email_username, email_password ]

matrix:
  PY:
    - 3.5
    - 3.6
    - 3.7
