stages:
  - testing
  - demo

.docker:
  tags:
    - docker-in-docker
    - long execution time
    - amm-only
  retry:
      max: 2
      when:
          - always
  image: docker:stable
  variables:
      DOCKER_HOST: tcp://docker:2375/
      DOCKER_DRIVER: overlay2
  before_script:
      - apk --update add openssh-client rsync git file make bash
      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
  services:
      - docker:dind
  environment:
      name: unsafe
  script:
      - make ${PY}
      - make push_${PY}

python 3.6:
  stage: testing
  extends: .docker
  variables:
      PY: "3.6"

python 3.7:
  extends: .docker
  stage: testing
  variables:
    PY: "3.7"

python 3.8:
  extends: .docker
  stage: testing
  variables:
    PY: "3.8"

python 3.9:
  extends: .docker
  stage: testing
  variables:
    PY: "3.9"
  allow_failure: true

master demo:
  extends: .docker
  stage: demo
  script:
    - make demo_master
    - make push_demo_master

py independent:
  extends: .docker
  stage: testing
  script:
    - make docker-in-docker
    - make push_docker-in-docker
