language: generic

notifications:
  email:
    on_success: change
    on_failure: change

sudo: required
services:
    - docker
os:
  - linux

env:
    global: DOCKER_IMAGE=quay.io/pypa/manylinux1_x86_64

    # we do not build wheels for:
    # cPython 2.6 - pymor's incompatible with it
    # cPython 3.3 - there's no scipy wheel for it
    matrix:
        - PYVER=cp34-cp34m
        - PYVER=cp35-cp35m
        - PYVER=cp27-cp27m
        - PYVER=cp27-cp27mu


install:
  - docker pull $DOCKER_IMAGE
  - git clone --branch=manifest_sdist_checking https://github.com/pymor/pymor

script:
  - docker run --rm -v `pwd`:/io -e PYVER="${PYVER}" $DOCKER_IMAGE /io/build-wheels.sh
  - ls wheelhouse/
