language: python

notifications:
  email:
    on_success: change
    on_failure: change

sudo: required
services: docker
os: linux

python:
    # we do not build wheels for:
    # cPython 2.6 - pymor's incompatible with it
    # cPython 3.3 - there's no scipy wheel for it
    - 2.7
    - 3.4
    - 3.5

script:
    - make ${TRAVIS_PYTHON_VERSION}
    - ls -l wheelhouse/*
