
sudo: required
dist: xenial
language: generic

script:
  - cd ${TRAVIS_BUILD_DIR}
  - git submodule update --init --recursive
  - git submodule status

notifications:
  email:
    on_success: change
    on_failure: change

git:
  # we do that manually in script section to be able to use our own git binary
  submodules: false
