language: generic

notifications:
  email:
    on_success: change
    on_failure: change

sudo: required
services: docker
os: linux

env:
    # we do not build wheels for:
    # cPython 2.6 - pymor's incompatible with it
    # cPython 3.3 - there's no scipy wheel for it
    - PYTHON_VERSION=2.7
    - PYTHON_VERSION=3.5
    - PYTHON_VERSION=3.6

script:
    - make ${PYTHON_VERSION}
    - ls -l wheelhouse/*

before_deploy:
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

deploy:
  - provider: script
    script: make push
    on:
        branch: master
