language: generic

notifications:
  email:
    on_success: change
    on_failure: change

sudo: required
services: docker
os: linux

# auto-updates docker engine
addons:
  apt:
    packages:
      - docker-ce

env:
    - PYTHON_VERSION=3.6
    - PYTHON_VERSION=3.7
    - PYTHON_VERSION=3.8

script:
    - make image${PYTHON_VERSION}

before_deploy:
    - docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD

deploy:
  - provider: script
    script: make push
    on:
        branch: master
