language: bash
services: docker

env:
  - VERSION=3.7 VARIANT=stretch-slim
  - VERSION=3.6 VARIANT=stretch-slim

install:
  - git clone https://github.com/docker-library/official-images.git ~/official-images

before_script:
  - env | sort
  - cd "$VERSION/$VARIANT"
  - export image="pymor/python:${VERSION}"

script:
  - |
    (
      set -Eeuo pipefail
      set -x
      travis_retry docker build -t "$image" .
      ~/official-images/test/run.sh -c ${TRAVIS_BUILD_DIR}/.ci/config.sh "$image"
    )
  - |
    if [[ "${TRAVIS_PULL_REQUEST}" == "false" ]] ; then
        docker login --username=$DOCKER_HUB_USERNAME --password=$DOCKER_HUB_PASSWORD
        docker push "$image"
    fi

after_script:
  - docker images

# vim:set et ts=2 sw=2:
