stages:
- stage: Testing
  pool:
    vmImage: 'ubuntu-16.04'
  jobs:
  - job: 'TestingImages'
    timeoutInMinutes: 0
    strategy:
      matrix:
        Python36:
          PY: '3.6'
        Python37:
          PY: '3.7'
          #Python38:
          #PY: '3.8'
      maxParallel: 4
    steps:
      - checkout: self
        submodules: true
      - task: Docker@1
        displayName: Container registry login
        inputs:
          command: login
          containerregistrytype: Container Registry
          dockerRegistryEndpoint: dockerhub

      # this makes testing images and upwards
      - script: make pull_all_latest_$(PY)
      - script: make $(PY)
      - script: make push_$(PY)

- stage: Demo
  pool:
    vmImage: 'ubuntu-16.04'
  jobs:
  - job: 'DemoImage'
    timeoutInMinutes: 0
    steps:
      - checkout: self
        submodules: true
      - task: Docker@1
        displayName: Container registry login
        inputs:
          command: login
          containerregistrytype: Container Registry
          dockerRegistryEndpoint: dockerhub

      # this makes testing images and upwards
      - script: make -C demo master
      - script: docker push pymor/demo:master
