version: '3'

# you should not use this file directly, but rather via the targets in the Makefile

services:
  test:
    depends_on:
      - pypi_mirror
    image: pymor/pypi-mirror_test_py${CNTR_BASE_PYTHON}:${CI_IMAGE_TAG}
    build:
        context: pypi-mirror_test
        dockerfile: Dockerfile
        args:
            BASE: pymor/testing_py${CNTR_BASE_PYTHON}:${CI_IMAGE_TAG}
            CONSTRAINTS_IMAGE: pymor/constraints_py${CNTR_BASE_PYTHON}:${CI_IMAGE_TAG}

    restart: "no"
    container_name: test_mirror_exec_${CNTR_BASE_PYTHON}_${CI_IMAGE_TAG}
    command: >
      bash -c 'pip install -r /requirements/requirements-optional.txt \
                -c /requirements/transformed_${VARIANT}_constraints.txt
              && python /usrl/local/bin/check_reqs.py /requirements/requirements-optional.txt
              && python /usrl/local/bin/check_import.py'

  pypi_mirror:
    image: pymor/pypi-mirror_${VARIANT}_py${CNTR_BASE_PYTHON}:${PYPI_MIRROR_TAG}
    restart: "no"
    container_name: test_mirror_${VARIANT}_${CNTR_BASE_PYTHON}_${CI_IMAGE_TAG}
