

stages:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"

#************ definition of base jobs *********************************************************************************#

.per_py:
    retry:
        max: 2
        when:
            - runner_system_failure
            - stuck_or_timeout_failure
            - api_failure

    tags:
      - amm-only_shell
    resource_group: cache_${PYVER}
    script:
      - make ${TARGET}_${PYVER} || (sleep 5s ; make ${TARGET}_${PYVER}) || (sleep 5s; make ${TARGET}_${PYVER})
      - make push_${TARGET}_${PYVER} || (sleep 5s ;  make push_${TARGET}_${PYVER}) || (sleep 5s ;  make push_${TARGET}_${PYVER} )

.py_indep:
    extends: .per_py
    script:
      - make ${TARGET} || (sleep 5s ; make ${TARGET}) || (sleep 5s; make ${TARGET})
      - make push_${TARGET} || (sleep 5s ;  make push_${TARGET}) || (sleep 5s ;  make push_${TARGET})





#******* stage 0

python_builder 3 6:
    extends: .per_py
    stage: "0"
    variables:
        PYVER: "3.6"
        TARGET: python_builder

python_builder 3 7:
    extends: .per_py
    stage: "0"
    variables:
        PYVER: "3.7"
        TARGET: python_builder

python_builder 3 8:
    extends: .per_py
    stage: "0"
    variables:
        PYVER: "3.8"
        TARGET: python_builder

deploy_checks:
    extends: .py_indep
    stage: "0"
    variables:
        TARGET: deploy_checks

#******* stage 1
ci_sanity:
    extends: .py_indep
    stage: "1"
    variables:
        TARGET: ci_sanity

python 3 6:
    extends: .per_py
    stage: "1"
    variables:
        PYVER: "3.6"
        TARGET: python

python 3 7:
    extends: .per_py
    stage: "1"
    variables:
        PYVER: "3.7"
        TARGET: python

python 3 8:
    extends: .per_py
    stage: "1"
    variables:
        PYVER: "3.8"
        TARGET: python


#******* stage 2

constraints 3 6:
    extends: .per_py
    stage: "2"
    variables:
        PYVER: "3.6"
        TARGET: constraints

constraints 3 7:
    extends: .per_py
    stage: "2"
    variables:
        PYVER: "3.7"
        TARGET: constraints

constraints 3 8:
    extends: .per_py
    stage: "2"
    variables:
        PYVER: "3.8"
        TARGET: constraints


dealii 3 6:
    extends: .per_py
    stage: "2"
    variables:
        PYVER: "3.6"
        TARGET: dealii

dealii 3 7:
    extends: .per_py
    stage: "2"
    variables:
        PYVER: "3.7"
        TARGET: dealii

dealii 3 8:
    extends: .per_py
    stage: "2"
    variables:
        PYVER: "3.8"
        TARGET: dealii


petsc 3 6:
    extends: .per_py
    stage: "2"
    variables:
        PYVER: "3.6"
        TARGET: petsc

petsc 3 7:
    extends: .per_py
    stage: "2"
    variables:
        PYVER: "3.7"
        TARGET: petsc

petsc 3 8:
    extends: .per_py
    stage: "2"
    variables:
        PYVER: "3.8"
        TARGET: petsc


#******* stage 3

pypi-mirror_stable 3 6:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "3.6"
        TARGET: pypi-mirror_stable

pypi-mirror_stable 3 7:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "3.7"
        TARGET: pypi-mirror_stable

pypi-mirror_stable 3 8:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "3.8"
        TARGET: pypi-mirror_stable


pypi-mirror_oldest 3 6:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "3.6"
        TARGET: pypi-mirror_oldest

pypi-mirror_oldest 3 7:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "3.7"
        TARGET: pypi-mirror_oldest

pypi-mirror_oldest 3 8:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "3.8"
        TARGET: pypi-mirror_oldest


ngsolve 3 6:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "3.6"
        TARGET: ngsolve

ngsolve 3 7:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "3.7"
        TARGET: ngsolve

ngsolve 3 8:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "3.8"
        TARGET: ngsolve


fenics 3 6:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "3.6"
        TARGET: fenics

fenics 3 7:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "3.7"
        TARGET: fenics

fenics 3 8:
    extends: .per_py
    stage: "3"
    variables:
        PYVER: "3.8"
        TARGET: fenics


#******* stage 4
wheelbuilder_manylinux1 3 6:
    extends: .per_py
    stage: "4"
    variables:
        PYVER: "3.6"
        TARGET: wheelbuilder_manylinux1

wheelbuilder_manylinux1 3 7:
    extends: .per_py
    stage: "4"
    variables:
        PYVER: "3.7"
        TARGET: wheelbuilder_manylinux1

wheelbuilder_manylinux1 3 8:
    extends: .per_py
    stage: "4"
    variables:
        PYVER: "3.8"
        TARGET: wheelbuilder_manylinux1


wheelbuilder_manylinux2010 3 6:
    extends: .per_py
    stage: "4"
    variables:
        PYVER: "3.6"
        TARGET: wheelbuilder_manylinux2010

wheelbuilder_manylinux2010 3 7:
    extends: .per_py
    stage: "4"
    variables:
        PYVER: "3.7"
        TARGET: wheelbuilder_manylinux2010

wheelbuilder_manylinux2010 3 8:
    extends: .per_py
    stage: "4"
    variables:
        PYVER: "3.8"
        TARGET: wheelbuilder_manylinux2010


wheelbuilder_manylinux2014 3 6:
    extends: .per_py
    stage: "4"
    variables:
        PYVER: "3.6"
        TARGET: wheelbuilder_manylinux2014

wheelbuilder_manylinux2014 3 7:
    extends: .per_py
    stage: "4"
    variables:
        PYVER: "3.7"
        TARGET: wheelbuilder_manylinux2014

wheelbuilder_manylinux2014 3 8:
    extends: .per_py
    stage: "4"
    variables:
        PYVER: "3.8"
        TARGET: wheelbuilder_manylinux2014



cibase 3 6:
    extends: .per_py
    stage: "4"
    variables:
        PYVER: "3.6"
        TARGET: cibase

cibase 3 7:
    extends: .per_py
    stage: "4"
    variables:
        PYVER: "3.7"
        TARGET: cibase

cibase 3 8:
    extends: .per_py
    stage: "4"
    variables:
        PYVER: "3.8"
        TARGET: cibase


#******* stage 5

testing 3 6:
    extends: .per_py
    stage: "5"
    variables:
        PYVER: "3.6"
        TARGET: testing

testing 3 7:
    extends: .per_py
    stage: "5"
    variables:
        PYVER: "3.7"
        TARGET: testing

testing 3 8:
    extends: .per_py
    stage: "5"
    variables:
        PYVER: "3.8"
        TARGET: testing

demo_master:
    extends: .py_indep
    stage: "5"
    variables:
        TARGET: demo_master

#******* stage 6

jupyter 3 6:
    extends: .per_py
    stage: "6"
    variables:
        PYVER: "3.6"
        TARGET: jupyter

jupyter 3 7:
    extends: .per_py
    stage: "6"
    variables:
        PYVER: "3.7"
        TARGET: jupyter

jupyter 3 8:
    extends: .per_py
    stage: "6"
    variables:
        PYVER: "3.8"
        TARGET: jupyter

docker-in-docker:
    extends: .py_indep
    stage: "6"
    variables:
        TARGET: docker-in-docker
docs:
    extends: .py_indep
    stage: "6"
    variables:
        TARGET: docs

# THIS FILE IS AUTOGENERATED -- DO NOT EDIT #
#   Edit and Re-run template.ci.py instead       #
