

stages:
  - "0"
  - "1"
  - "2"
  - "3"
  - "4"
  - "5"
  - "6"

#************ definition of base jobs *********************************************************************************#

.per_py:
    retry:
        max: 2
        when:
            - runner_system_failure
            - stuck_or_timeout_failure
            - api_failure

    tags:
      - long execution time
      - docker-in-docker
    script:
      - make ${TARGET}_${PYVER}
      - make push_${TARGET}_${PYVER}
    before_script:
      - apk --update add openssh-client rsync git file make bash m4
      - docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_PASSWORD
      - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
      - docker version
      - docker buildx
    variables:
        DOCKER_HOST: tcp://docker:2375/
        DOCKER_DRIVER: overlay2
        DOCKER_CLI_EXPERIMENTAL: enabled
    image: pymor/docker-in-docker:e85eee354d268bb406d381155964d0fbcdf7161f
    services:
        - name: docker:dind
          command: ["--experimental"]

.py_indep:
    extends: .per_py
    script:
      - make ${TARGET}
      - make push_${TARGET}





#******* stage 0

python_builder 3 6:
    extends: .per_py
    stage: "0"
    tags:
    
          - mike
    variables:
        PYVER: "3.6"
        TARGET: python_builder

python_builder 3 7:
    extends: .per_py
    stage: "0"
    tags:
    
          - mike
    variables:
        PYVER: "3.7"
        TARGET: python_builder

python_builder 3 8:
    extends: .per_py
    stage: "0"
    tags:
    
          - mike
    variables:
        PYVER: "3.8"
        TARGET: python_builder

deploy_checks:
    extends: .py_indep
    stage: "0"
    variables:
        TARGET: deploy_checks

#******* stage 1
ci_sanity:
    extends: .py_indep
    stage: "1"
    variables:
        TARGET: ci_sanity

python 3 6:
    extends: .per_py
    stage: "1"
    tags:
    
          - mike
    variables:
        PYVER: "3.6"
        TARGET: python

python 3 7:
    extends: .per_py
    stage: "1"
    tags:
    
          - mike
    variables:
        PYVER: "3.7"
        TARGET: python

python 3 8:
    extends: .per_py
    stage: "1"
    tags:
    
          - mike
    variables:
        PYVER: "3.8"
        TARGET: python


#******* stage 2

constraints 3 6:
    extends: .per_py
    stage: "2"
    tags:
    
          - mike
    variables:
        PYVER: "3.6"
        TARGET: constraints

constraints 3 7:
    extends: .per_py
    stage: "2"
    tags:
    
          - mike
    variables:
        PYVER: "3.7"
        TARGET: constraints

constraints 3 8:
    extends: .per_py
    stage: "2"
    tags:
    
          - mike
    variables:
        PYVER: "3.8"
        TARGET: constraints


dealii 3 6:
    extends: .per_py
    stage: "2"
    tags:
    
          - mike
    variables:
        PYVER: "3.6"
        TARGET: dealii

dealii 3 7:
    extends: .per_py
    stage: "2"
    tags:
    
          - mike
    variables:
        PYVER: "3.7"
        TARGET: dealii

dealii 3 8:
    extends: .per_py
    stage: "2"
    tags:
    
          - mike
    variables:
        PYVER: "3.8"
        TARGET: dealii


petsc 3 6:
    extends: .per_py
    stage: "2"
    tags:
    
          - mike
    variables:
        PYVER: "3.6"
        TARGET: petsc

petsc 3 7:
    extends: .per_py
    stage: "2"
    tags:
    
          - mike
    variables:
        PYVER: "3.7"
        TARGET: petsc

petsc 3 8:
    extends: .per_py
    stage: "2"
    tags:
    
          - mike
    variables:
        PYVER: "3.8"
        TARGET: petsc


#******* stage 3

pypi-mirror_stable 3 6:
    extends: .per_py
    stage: "3"
    tags:
    
          - mike
    variables:
        PYVER: "3.6"
        TARGET: pypi-mirror_stable

pypi-mirror_stable 3 7:
    extends: .per_py
    stage: "3"
    tags:
    
          - mike
    variables:
        PYVER: "3.7"
        TARGET: pypi-mirror_stable

pypi-mirror_stable 3 8:
    extends: .per_py
    stage: "3"
    tags:
    
          - mike
    variables:
        PYVER: "3.8"
        TARGET: pypi-mirror_stable


pypi-mirror_oldest 3 6:
    extends: .per_py
    stage: "3"
    tags:
    
          - mike
    variables:
        PYVER: "3.6"
        TARGET: pypi-mirror_oldest

pypi-mirror_oldest 3 7:
    extends: .per_py
    stage: "3"
    tags:
    
          - mike
    variables:
        PYVER: "3.7"
        TARGET: pypi-mirror_oldest

pypi-mirror_oldest 3 8:
    extends: .per_py
    stage: "3"
    tags:
    
          - mike
    variables:
        PYVER: "3.8"
        TARGET: pypi-mirror_oldest


ngsolve 3 6:
    extends: .per_py
    stage: "3"
    tags:
    
          - mike
    variables:
        PYVER: "3.6"
        TARGET: ngsolve

ngsolve 3 7:
    extends: .per_py
    stage: "3"
    tags:
    
          - mike
    variables:
        PYVER: "3.7"
        TARGET: ngsolve

ngsolve 3 8:
    extends: .per_py
    stage: "3"
    tags:
    
          - mike
    variables:
        PYVER: "3.8"
        TARGET: ngsolve


fenics 3 6:
    extends: .per_py
    stage: "3"
    tags:
    
          - mike
    variables:
        PYVER: "3.6"
        TARGET: fenics

fenics 3 7:
    extends: .per_py
    stage: "3"
    tags:
    
          - mike
    variables:
        PYVER: "3.7"
        TARGET: fenics

fenics 3 8:
    extends: .per_py
    stage: "3"
    tags:
    
          - mike
    variables:
        PYVER: "3.8"
        TARGET: fenics


#******* stage 4
wheelbuilder_manylinux2010 3 6:
    extends: .per_py
    stage: "4"
    tags:
    
          - mike
    variables:
        PYVER: "3.6"
        TARGET: wheelbuilder_manylinux2010

wheelbuilder_manylinux2010 3 7:
    extends: .per_py
    stage: "4"
    tags:
    
          - mike
    variables:
        PYVER: "3.7"
        TARGET: wheelbuilder_manylinux2010

wheelbuilder_manylinux2010 3 8:
    extends: .per_py
    stage: "4"
    tags:
    
          - mike
    variables:
        PYVER: "3.8"
        TARGET: wheelbuilder_manylinux2010


wheelbuilder_manylinux2014 3 6:
    extends: .per_py
    stage: "4"
    tags:
    
          - mike
    variables:
        PYVER: "3.6"
        TARGET: wheelbuilder_manylinux2014

wheelbuilder_manylinux2014 3 7:
    extends: .per_py
    stage: "4"
    tags:
    
          - mike
    variables:
        PYVER: "3.7"
        TARGET: wheelbuilder_manylinux2014

wheelbuilder_manylinux2014 3 8:
    extends: .per_py
    stage: "4"
    tags:
    
          - mike
    variables:
        PYVER: "3.8"
        TARGET: wheelbuilder_manylinux2014



cibase 3 6:
    extends: .per_py
    stage: "4"
    tags:
    
          - mike
    variables:
        PYVER: "3.6"
        TARGET: cibase

cibase 3 7:
    extends: .per_py
    stage: "4"
    tags:
    
          - mike
    variables:
        PYVER: "3.7"
        TARGET: cibase

cibase 3 8:
    extends: .per_py
    stage: "4"
    tags:
    
          - mike
    variables:
        PYVER: "3.8"
        TARGET: cibase


#******* stage 5

testing 3 6:
    extends: .per_py
    stage: "5"
    tags:
    
          - mike
    variables:
        PYVER: "3.6"
        TARGET: testing

testing 3 7:
    extends: .per_py
    stage: "5"
    tags:
    
          - mike
    variables:
        PYVER: "3.7"
        TARGET: testing

testing 3 8:
    extends: .per_py
    stage: "5"
    tags:
    
          - mike
    variables:
        PYVER: "3.8"
        TARGET: testing

demo_master:
    extends: .py_indep
    stage: "5"
    variables:
        TARGET: demo_master

#******* stage 6

jupyter 3 6:
    extends: .per_py
    stage: "6"
    tags:
    
          - mike
    variables:
        PYVER: "3.6"
        TARGET: jupyter

jupyter 3 7:
    extends: .per_py
    stage: "6"
    tags:
    
          - mike
    variables:
        PYVER: "3.7"
        TARGET: jupyter

jupyter 3 8:
    extends: .per_py
    stage: "6"
    tags:
    
          - mike
    variables:
        PYVER: "3.8"
        TARGET: jupyter

docker-in-docker:
    extends: .py_indep
    stage: "6"
    variables:
        TARGET: docker-in-docker
docs:
    extends: .py_indep
    stage: "6"
    variables:
        TARGET: docs

# THIS FILE IS AUTOGENERATED -- DO NOT EDIT #
#   Edit and Re-run template.ci.py instead       #
